POST http://localhost:5000/api/comments
Content-Type: application/json

{

    "blogId":1,
    "commentId":0,
    "name":"Nguyen Tien Tai",
    "email":"nguyentientai10@gmail.com",
    "body":"Content... so great!"
}

###
POST http://localhost:5000/api/commentMany
Content-Type: application/json

{

}

###
GET http://localhost:5000/api/list?blogId=1&page=2&pagesize=50
Content-Type: application/json

{

}




/// HackNew

###
GET http://localhost:5000/api/listhacknews?commentId=30&pagesize=50
Content-Type: application/json

{

}



